/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum CommandType
{
  Unknown = 0,
  Nothing = 1,
  Register = 2,
  Free = 3,
  Delete = 4,
  Persist = 5,
}
