/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class CommandLineJobInfo : TBase
{
  private string _command;
  private JobConfInfo _conf;

  public string Command
  {
    get
    {
      return _command;
    }
    set
    {
      __isset.command = true;
      this._command = value;
    }
  }

  public JobConfInfo Conf
  {
    get
    {
      return _conf;
    }
    set
    {
      __isset.conf = true;
      this._conf = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool command;
    public bool conf;
  }

  public CommandLineJobInfo() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Command = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Struct) {
              Conf = new JobConfInfo();
              Conf.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("CommandLineJobInfo");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Command != null && __isset.command) {
        field.Name = "command";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Command);
        oprot.WriteFieldEnd();
      }
      if (Conf != null && __isset.conf) {
        field.Name = "conf";
        field.Type = TType.Struct;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        Conf.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("CommandLineJobInfo(");
    bool __first = true;
    if (Command != null && __isset.command) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Command: ");
      __sb.Append(Command);
    }
    if (Conf != null && __isset.conf) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Conf: ");
      __sb.Append(Conf);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

