/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class CreateFileTOptions : TBase
{
  private long _blockSizeBytes;
  private bool _persisted;
  private bool _recursive;
  private long _ttl;

  public long BlockSizeBytes
  {
    get
    {
      return _blockSizeBytes;
    }
    set
    {
      __isset.blockSizeBytes = true;
      this._blockSizeBytes = value;
    }
  }

  public bool Persisted
  {
    get
    {
      return _persisted;
    }
    set
    {
      __isset.persisted = true;
      this._persisted = value;
    }
  }

  public bool Recursive
  {
    get
    {
      return _recursive;
    }
    set
    {
      __isset.recursive = true;
      this._recursive = value;
    }
  }

  public long Ttl
  {
    get
    {
      return _ttl;
    }
    set
    {
      __isset.ttl = true;
      this._ttl = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool blockSizeBytes;
    public bool persisted;
    public bool recursive;
    public bool ttl;
  }

  public CreateFileTOptions() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              BlockSizeBytes = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Bool) {
              Persisted = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Bool) {
              Recursive = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I64) {
              Ttl = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("CreateFileTOptions");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.blockSizeBytes) {
        field.Name = "blockSizeBytes";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(BlockSizeBytes);
        oprot.WriteFieldEnd();
      }
      if (__isset.persisted) {
        field.Name = "persisted";
        field.Type = TType.Bool;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(Persisted);
        oprot.WriteFieldEnd();
      }
      if (__isset.recursive) {
        field.Name = "recursive";
        field.Type = TType.Bool;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(Recursive);
        oprot.WriteFieldEnd();
      }
      if (__isset.ttl) {
        field.Name = "ttl";
        field.Type = TType.I64;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(Ttl);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("CreateFileTOptions(");
    bool __first = true;
    if (__isset.blockSizeBytes) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("BlockSizeBytes: ");
      __sb.Append(BlockSizeBytes);
    }
    if (__isset.persisted) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Persisted: ");
      __sb.Append(Persisted);
    }
    if (__isset.recursive) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Recursive: ");
      __sb.Append(Recursive);
    }
    if (__isset.ttl) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Ttl: ");
      __sb.Append(Ttl);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

