/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class CreateDirectoryTOptions : TBase
{
  private bool _persisted;
  private bool _recursive;
  private bool _allowExists;

  public bool Persisted
  {
    get
    {
      return _persisted;
    }
    set
    {
      __isset.persisted = true;
      this._persisted = value;
    }
  }

  public bool Recursive
  {
    get
    {
      return _recursive;
    }
    set
    {
      __isset.recursive = true;
      this._recursive = value;
    }
  }

  public bool AllowExists
  {
    get
    {
      return _allowExists;
    }
    set
    {
      __isset.allowExists = true;
      this._allowExists = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool persisted;
    public bool recursive;
    public bool allowExists;
  }

  public CreateDirectoryTOptions() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Bool) {
              Persisted = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Bool) {
              Recursive = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Bool) {
              AllowExists = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("CreateDirectoryTOptions");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.persisted) {
        field.Name = "persisted";
        field.Type = TType.Bool;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(Persisted);
        oprot.WriteFieldEnd();
      }
      if (__isset.recursive) {
        field.Name = "recursive";
        field.Type = TType.Bool;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(Recursive);
        oprot.WriteFieldEnd();
      }
      if (__isset.allowExists) {
        field.Name = "allowExists";
        field.Type = TType.Bool;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(AllowExists);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("CreateDirectoryTOptions(");
    bool __first = true;
    if (__isset.persisted) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Persisted: ");
      __sb.Append(Persisted);
    }
    if (__isset.recursive) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Recursive: ");
      __sb.Append(Recursive);
    }
    if (__isset.allowExists) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("AllowExists: ");
      __sb.Append(AllowExists);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

