/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class FileSystemCommand : TBase
{
  private CommandType _commandType;
  private FileSystemCommandOptions _commandOptions;

  /// <summary>
  /// 
  /// <seealso cref=".CommandType"/>
  /// </summary>
  public CommandType CommandType
  {
    get
    {
      return _commandType;
    }
    set
    {
      __isset.commandType = true;
      this._commandType = value;
    }
  }

  public FileSystemCommandOptions CommandOptions
  {
    get
    {
      return _commandOptions;
    }
    set
    {
      __isset.commandOptions = true;
      this._commandOptions = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool commandType;
    public bool commandOptions;
  }

  public FileSystemCommand() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              CommandType = (CommandType)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Struct) {
              CommandOptions = new FileSystemCommandOptions();
              CommandOptions.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("FileSystemCommand");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.commandType) {
        field.Name = "commandType";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)CommandType);
        oprot.WriteFieldEnd();
      }
      if (CommandOptions != null && __isset.commandOptions) {
        field.Name = "commandOptions";
        field.Type = TType.Struct;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        CommandOptions.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("FileSystemCommand(");
    bool __first = true;
    if (__isset.commandType) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("CommandType: ");
      __sb.Append(CommandType);
    }
    if (CommandOptions != null && __isset.commandOptions) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("CommandOptions: ");
      __sb.Append(CommandOptions);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

