/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class ListStatusTOptions : TBase
{
  private bool _loadDirectChildren;
  private LoadMetadataTType _loadMetadataType;

  public bool LoadDirectChildren
  {
    get
    {
      return _loadDirectChildren;
    }
    set
    {
      __isset.loadDirectChildren = true;
      this._loadDirectChildren = value;
    }
  }

  /// <summary>
  /// 
  /// <seealso cref="LoadMetadataTType"/>
  /// </summary>
  public LoadMetadataTType LoadMetadataType
  {
    get
    {
      return _loadMetadataType;
    }
    set
    {
      __isset.loadMetadataType = true;
      this._loadMetadataType = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool loadDirectChildren;
    public bool loadMetadataType;
  }

  public ListStatusTOptions() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Bool) {
              LoadDirectChildren = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              LoadMetadataType = (LoadMetadataTType)iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("ListStatusTOptions");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.loadDirectChildren) {
        field.Name = "loadDirectChildren";
        field.Type = TType.Bool;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(LoadDirectChildren);
        oprot.WriteFieldEnd();
      }
      if (__isset.loadMetadataType) {
        field.Name = "loadMetadataType";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)LoadMetadataType);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("ListStatusTOptions(");
    bool __first = true;
    if (__isset.loadDirectChildren) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("LoadDirectChildren: ");
      __sb.Append(LoadDirectChildren);
    }
    if (__isset.loadMetadataType) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("LoadMetadataType: ");
      __sb.Append(LoadMetadataType);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

