/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class PersistFile : TBase
{
  private long _fileId;
  private List<long> _blockIds;

  public long FileId
  {
    get
    {
      return _fileId;
    }
    set
    {
      __isset.fileId = true;
      this._fileId = value;
    }
  }

  public List<long> BlockIds
  {
    get
    {
      return _blockIds;
    }
    set
    {
      __isset.blockIds = true;
      this._blockIds = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool fileId;
    public bool blockIds;
  }

  public PersistFile() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              FileId = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                BlockIds = new List<long>();
                TList _list25 = iprot.ReadListBegin();
                for( int _i26 = 0; _i26 < _list25.Count; ++_i26)
                {
                  long _elem27;
                  _elem27 = iprot.ReadI64();
                  BlockIds.Add(_elem27);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("PersistFile");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.fileId) {
        field.Name = "fileId";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(FileId);
        oprot.WriteFieldEnd();
      }
      if (BlockIds != null && __isset.blockIds) {
        field.Name = "blockIds";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.I64, BlockIds.Count));
          foreach (long _iter28 in BlockIds)
          {
            oprot.WriteI64(_iter28);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("PersistFile(");
    bool __first = true;
    if (__isset.fileId) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("FileId: ");
      __sb.Append(FileId);
    }
    if (BlockIds != null && __isset.blockIds) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("BlockIds: ");
      __sb.Append(BlockIds);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

