/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class PersistCommandOptions : TBase
{
  private List<PersistFile> _persistFiles;

  public List<PersistFile> PersistFiles
  {
    get
    {
      return _persistFiles;
    }
    set
    {
      __isset.persistFiles = true;
      this._persistFiles = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool persistFiles;
  }

  public PersistCommandOptions() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                PersistFiles = new List<PersistFile>();
                TList _list21 = iprot.ReadListBegin();
                for( int _i22 = 0; _i22 < _list21.Count; ++_i22)
                {
                  PersistFile _elem23;
                  _elem23 = new PersistFile();
                  _elem23.Read(iprot);
                  PersistFiles.Add(_elem23);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("PersistCommandOptions");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (PersistFiles != null && __isset.persistFiles) {
        field.Name = "persistFiles";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, PersistFiles.Count));
          foreach (PersistFile _iter24 in PersistFiles)
          {
            _iter24.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("PersistCommandOptions(");
    bool __first = true;
    if (PersistFiles != null && __isset.persistFiles) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("PersistFiles: ");
      __sb.Append(PersistFiles);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

